#pragma once
//Dymatic C++ Include Script

#include "DymaticNodeLibrary.h"
#include "Dymatic/Scene/ScriptableEntity.h"

class BlueprintClass : public ScriptableEntity
{
public:
//Variables
bool DymaticNodeVariable_Test_Bool = true;
float DymaticNodeVariable_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91_ = 5.423000f;
int DymaticNodeVariable_Test_Int = 12;

//Custom Node Library Additions
FunctionReturn DymaticVariable_Get_Test_Bool(FunctionReturn functionIn)
{FunctionReturn returnVal;
returnVal.PinValues.push_back({});
returnVal.PinValues[0].Bool = DymaticNodeVariable_Test_Bool;
return returnVal;
}

FunctionReturn DymaticVariable_Set_Test_Bool(FunctionReturn functionIn)
{FunctionReturn returnVal;
returnVal.PinValues.push_back({});
returnVal.PinValues.push_back({});
DymaticNodeVariable_Test_Bool = functionIn.PinValues[1].Bool;
returnVal.PinValues[1].Bool = DymaticNodeVariable_Test_Bool;
return returnVal;
}

FunctionReturn DymaticVariable_Get_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91_(FunctionReturn functionIn)
{FunctionReturn returnVal;
returnVal.PinValues.push_back({});
returnVal.PinValues[0].Float = DymaticNodeVariable_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91_;
return returnVal;
}

FunctionReturn DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91_(FunctionReturn functionIn)
{FunctionReturn returnVal;
returnVal.PinValues.push_back({});
returnVal.PinValues.push_back({});
DymaticNodeVariable_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91_ = functionIn.PinValues[1].Float;
returnVal.PinValues[1].Float = DymaticNodeVariable_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91_;
return returnVal;
}

FunctionReturn DymaticVariable_Get_Test_Int(FunctionReturn functionIn)
{FunctionReturn returnVal;
returnVal.PinValues.push_back({});
returnVal.PinValues[0].Int = DymaticNodeVariable_Test_Int;
return returnVal;
}

FunctionReturn DymaticVariable_Set_Test_Int(FunctionReturn functionIn)
{FunctionReturn returnVal;
returnVal.PinValues.push_back({});
returnVal.PinValues.push_back({});
DymaticNodeVariable_Test_Int = functionIn.PinValues[1].Int;
returnVal.PinValues[1].Int = DymaticNodeVariable_Test_Int;
return returnVal;
}


//Function Save States
FunctionReturn s_NodeEditorFunctionSave_On_Create_63;
FunctionReturn s_NodeEditorFunctionSave_DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91__65;
FunctionReturn s_NodeEditorFunctionSave_Print_String_71;
FunctionReturn s_NodeEditorFunctionSave_Float_To_String_76;
FunctionReturn NodeEvent_On_Create_63 ();

FunctionReturn NodeEvent_DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91__65 ();

FunctionReturn NodeEvent_Print_String_71 ();

FunctionReturn NodeEvent_Float_To_String_76 ();

virtual void OnCreate() override
{
NodeEvent_On_Create_63();
}

virtual void OnUpdate(Timestep ts) override
{
}

};

FunctionReturn BlueprintClass::NodeEvent_On_Create_63 ()
{
for (int index : (s_NodeEditorFunctionSave_On_Create_63 = On_Create(s_NodeEditorFunctionSave_On_Create_63)).Executable){switch (index){
case 0: { NodeEvent_DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91__65(); break; }
};
};

return s_NodeEditorFunctionSave_On_Create_63;

}
FunctionReturn BlueprintClass::NodeEvent_DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91__65 ()
{
s_NodeEditorFunctionSave_DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91__65.PinValues.push_back({});
s_NodeEditorFunctionSave_DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91__65.PinValues.push_back({});
s_NodeEditorFunctionSave_DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91__65.PinValues[1].Float = 23.500000f;
for (int index : (s_NodeEditorFunctionSave_DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91__65 = DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91_(s_NodeEditorFunctionSave_DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91__65)).Executable){switch (index){
case 0: { NodeEvent_Print_String_71(); break; }
};
};

return s_NodeEditorFunctionSave_DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91__65;

}
FunctionReturn BlueprintClass::NodeEvent_Print_String_71 ()
{
s_NodeEditorFunctionSave_Print_String_71.PinValues.push_back({});
s_NodeEditorFunctionSave_Print_String_71.PinValues.push_back({});
s_NodeEditorFunctionSave_Print_String_71.PinValues[1].String = NodeEvent_Float_To_String_76().PinValues[0].String;
for (int index : (s_NodeEditorFunctionSave_Print_String_71 = Print_String(s_NodeEditorFunctionSave_Print_String_71)).Executable){switch (index){
};
};

return s_NodeEditorFunctionSave_Print_String_71;

}
FunctionReturn BlueprintClass::NodeEvent_Float_To_String_76 ()
{
s_NodeEditorFunctionSave_Float_To_String_76.PinValues.push_back({});
s_NodeEditorFunctionSave_Float_To_String_76.PinValues[0].Float = s_NodeEditorFunctionSave_DymaticVariable_Set_Test_Float_Dollar_Sign_36___Ampersand_38__Left_Parenthesis_40__Hashtag_35__Ampersand_38__Left_Parenthesis_40__Dollar_Sign_36__Ampersand_38__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Dollar_Sign_36__Left_Parenthesis_40__Asterisk_42__Asterisk_42__Dollar_Sign_36__Left_Parenthesis_40__Hashtag_35__Left_Parenthesis_40__Asterisk_42_89fnf_f_dfsfds_Asterisk_42__Right_Parenthesis_41__Left_Parenthesis_40__Right_Parenthesis_41__Dollar_Sign_36__At_Sign_64__Left_Parenthesis_40__Asterisk_42__Vertical_Bar_124__Vertical_Bar_124__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Right_Curly_Bracket_125__Backslash_92__Backslash_92__Backslash_92__Left_Square_Bracket_91__Left_Square_Bracket_91__65.PinValues[1].Float;
s_NodeEditorFunctionSave_Float_To_String_76 = Float_To_String(s_NodeEditorFunctionSave_Float_To_String_76);
return s_NodeEditorFunctionSave_Float_To_String_76;

}
