#pragma once

//Basic Symbols

#define CHARACTER_SYMBOL_DEGREE u8"\u00B0"

// Window Icons
#define CHARACTER_WINDOW_ICON_STATS u8"\u0700"
#define CHARACTER_WINDOW_ICON_PROPERTIES u8"\u0701"
#define CHARACTER_WINDOW_ICON_PREFERENCES u8"\u0702"
#define CHARACTER_WINDOW_ICON_VIEWPORT u8"\u0703"
#define CHARACTER_WINDOW_ICON_INFO u8"\u0704"
#define CHARACTER_WINDOW_ICON_CONTENT_BROWSER u8"\u0705"
#define CHARACTER_WINDOW_ICON_SCENE_HIERARCHY u8"\u0706"
#define CHARACTER_WINDOW_ICON_CURVE_EDITOR u8"\u0707"
#define CHARACTER_WINDOW_ICON_NODE_EDITOR u8"\u0708"
#define CHARACTER_WINDOW_ICON_TEXT_EDITOR u8"\u0709"
#define CHARACTER_WINDOW_ICON_TOOLBAR u8"\u070A"
#define CHARACTER_WINDOW_ICON_NOTIFICATIONS u8"\u070B"
#define CHARACTER_WINDOW_ICON_CONSOLE u8"\u070C"
#define CHARACTER_WINDOW_ICON_IMAGE_EDITOR u8"\u070D"
#define CHARACTER_WINDOW_ICON_MEMORY_EDITOR u8"\u070E"
#define CHARACTER_WINDOW_ICON_SYSTEM_CONSOLE u8"\u070F"

// Viewport Icons
#define CHARACTER_VIEWPORT_ICON_SHADING_WIREFRAME u8"\u0710"
#define CHARACTER_VIEWPORT_ICON_SHADING_UNLIT u8"\u0711"
#define CHARACTER_VIEWPORT_ICON_SHADING_SOLID u8"\u0712"
#define CHARACTER_VIEWPORT_ICON_SHADING_RENDERED u8"\u0713"

#define CHARACTER_VIEWPORT_ICON_GIZMO_CURSOR u8"\u0714"
#define CHARACTER_VIEWPORT_ICON_GIZMO_TRANSLATE u8"\u0715"
#define CHARACTER_VIEWPORT_ICON_GIZMO_ROTATE u8"\u0716"
#define CHARACTER_VIEWPORT_ICON_GIZMO_SCALE u8"\u0717"
#define CHARACTER_VIEWPORT_ICON_SPACE_LOCAL u8"\u0718"
#define CHARACTER_VIEWPORT_ICON_SPACE_WORLD u8"\u0719"
#define CHARACTER_VIEWPORT_ICON_SNAP_TRANSLATION u8"\u071A"
#define CHARACTER_VIEWPORT_ICON_SNAP_ROTATION u8"\u071B"
#define CHARACTER_VIEWPORT_ICON_SNAP_SCALING u8"\u071C"
#define CHARACTER_VIEWPORT_ICON_PROJECTION_ORTHOGRAPHIC u8"\u071D"
#define CHARACTER_VIEWPORT_ICON_PROJECTION_PERSPECTIVE u8"\u071E"


#define CHARACTER_ICON_DYMATIC u8"\u071F"

// System Icons

#define CHARACTER_SYSTEM_ICON_NEW_FILE u8"\u0720"
#define CHARACTER_SYSTEM_ICON_OPEN_FILE u8"\u0721"
#define CHARACTER_SYSTEM_ICON_RECENT u8"\u0722"
#define CHARACTER_SYSTEM_ICON_SAVE u8"\u0723"
#define CHARACTER_SYSTEM_ICON_SAVE_AS u8"\u0724"
#define CHARACTER_SYSTEM_ICON_IMPORT u8"\u0725"
#define CHARACTER_SYSTEM_ICON_EXPORT u8"\u0726"
#define CHARACTER_SYSTEM_ICON_APPEND u8"\u0727"
#define CHARACTER_SYSTEM_ICON_QUIT u8"\u0728"

//Properties Icons

#define CHARACTER_PROPERTIES_ICON_ADD u8"\u0729"
#define CHARACTER_PROPERTIES_ICON_DUPLICATE u8"\u072A"
#define CHARACTER_PROPERTIES_ICON_DELETE u8"\u072B"