#pragma once

//Window Icons
#define CHARACTER_LAUNCHER_ICON_HOME u8"\u0700"
#define CHARACTER_LAUNCHER_ICON_ENGINE u8"\u0701"
#define CHARACTER_LAUNCHER_ICON_STORE u8"\u0702"
#define CHARACTER_LAUNCHER_ICON_LIBRARY u8"\u0703"
#define CHARACTER_LAUNCHER_ICON_SETTINGS u8"\u0704"

#define CHARACTER_LAUNCHER_ICON_NO_INTERNET u8"\u0705"